// Lab content — inline backticks replaced with \u0060 to avoid template literal conflicts

const bt = "\u0060"; // single backtick
const bt3 = "\u0060\u0060\u0060"; // triple backtick

export const labContents: Record<string, string> = {

"cg-lab-1-opengl-installation": [
"## What is OpenGL?",
"",
"OpenGL (Open Graphics Library) is a cross-platform, open-standard API for rendering 2D and 3D graphics. It acts as a bridge between your code and the GPU, giving you direct control over how graphics are drawn on screen.",
"",
"In this course we use OpenGL with **GLUT (OpenGL Utility Toolkit)** — specifically the **freeglut** library — inside **CodeBlocks IDE** on Windows.",
"",
"> OpenGL doesn't create windows or handle user input by itself. GLUT handles the window creation, keyboard/mouse events, and the main loop for us.",
"",
"## Prerequisites",
"",
"Before installing, make sure you have:",
"",
"- **CodeBlocks IDE** (version 20.03 or later recommended)",
"- **MinGW compiler** bundled with CodeBlocks",
"- Windows OS (these steps are Windows-specific)",
"",
"## Installation Steps",
"",
"### Step 1 — Download freeglut",
"",
"Go to: https://www.transmissionzero.co.uk/software/freeglut-devel/",
"",
"Download the **MinGW package** (freeglut 3.x for MinGW).",
"",
"### Step 2 — Copy the files",
"",
"Extract the downloaded zip. Copy the files to these locations:",
"",
bt3,
"freeglut/include/GL/  →  C:/MinGW/include/GL/",
"freeglut/lib/         →  C:/MinGW/lib/",
"freeglut/bin/freeglut.dll  →  C:/Windows/System32/",
bt3,
"",
"### Step 3 — Configure CodeBlocks linker",
"",
"In CodeBlocks:",
"- Go to **Settings → Compiler → Linker settings**",
"- Add these libraries in Other linker options:",
"",
bt3,
"-lglut32 -lglu32 -lopengl32",
bt3,
"",
`Or add them as link libraries: ${bt}libglut32.a${bt}, ${bt}libglu32.a${bt}, ${bt}libopengl32.a${bt}`,
"",
"### Step 4 — Set compiler flags (optional)",
"",
`Add ${bt}-DFREEGLUT_STATIC${bt} if you want static linking. Usually not needed.`,
"",
"## First OpenGL Window",
"",
"Here is the minimal code to open an OpenGL window and draw a white background:",
"",
bt3 + "cpp",
"#include <GL/glut.h>",
"",
"void display() {",
"    glClear(GL_COLOR_BUFFER_BIT);",
"    glFlush();",
"}",
"",
"void init() {",
"    glClearColor(1.0, 1.0, 1.0, 1.0); // white background",
"}",
"",
"int main(int argc, char** argv) {",
"    glutInit(&argc, argv);",
"    glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);",
"    glutInitWindowSize(500, 400);",
'    glutCreateWindow("My First OpenGL Window");',
"    init();",
"    glutDisplayFunc(display);",
"    glutMainLoop();",
"    return 0;",
"}",
bt3,
"",
"If everything is set up correctly, you will see a white window appear. That is your first success!",
"",
"## Troubleshooting",
"",
"| Problem | Solution |",
"| --- | --- |",
`| ${bt}freeglut.dll not found${bt} | Copy ${bt}freeglut.dll${bt} to ${bt}C:/Windows/System32/${bt} |`,
`| ${bt}undefined reference to glutInit${bt} | Add ${bt}-lglut32${bt} to linker settings |`,
`| Black screen instead of white | Check ${bt}glClearColor()${bt} call in ${bt}init()${bt} |`,
`| CodeBlocks can't find GL/glut.h | Verify files are in ${bt}C:/MinGW/include/GL/${bt} |`,
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-2-image-basics": [
"## What is a Digital Image?",
"",
"A digital image is a 2D array of pixels. Each pixel holds intensity values — for a grayscale image it's one value (0–255), for an RGB image it's three values (R, G, B).",
"",
`In Python, **OpenCV** represents images as NumPy arrays with shape ${bt}(height, width, channels)${bt}.`,
"",
"> All examples below use **Fig0630 — Strawberries** from Gonzalez's Digital Image Processing book (Fig. 6.30). You can use any `.png` or `.jpg` file.",
"",
"## Read & Display Image",
"",
bt3 + "python",
"import cv2",
"import matplotlib.pyplot as plt",
"",
"img = cv2.imread('strawberries.png')      # reads as BGR",
"img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)",
"",
"plt.imshow(img_rgb)",
"plt.title('Strawberries — Original')",
"plt.axis('off')",
"plt.show()",
bt3,
"",
"**Why convert BGR to RGB?** OpenCV loads images in BGR order, but Matplotlib expects RGB. Without conversion, the red and blue channels are swapped and colors look wrong.",
"",
"**Benefits:**",
"- Simple one-line image loading",
"- Supports JPEG, PNG, BMP, TIFF and more",
"",
"**Drawback:**",
"- OpenCV uses BGR instead of the more common RGB order",
"",
"## Image Dimensions (RGB)",
"",
bt3 + "python",
'print(f"Shape    : {img.shape}")    # (height, width, channels)',
'print(f"Height   : {img.shape[0]} px")',
'print(f"Width    : {img.shape[1]} px")',
'print(f"Channels : {img.shape[2]}")  # 3 = RGB/BGR, 1 = Grayscale',
'print(f"Total pixels: {img.shape[0] * img.shape[1]}")',
bt3,
"",
"For the Strawberries image (Fig0630) the output is:",
"",
bt3,
"Shape    : (666, 666, 3)",
"Height   : 666 px",
"Width    : 666 px",
"Channels : 3",
"Total pixels: 443556",
bt3,
"",
"## Load from PC Storage",
"",
"> No visual output for this task — it is code-only. The image loads silently into memory.",
"",
bt3 + "python",
"import os",
"",
'image_path = r"C:\\Users\\USER\\Pictures\\sample.jpg"',
"",
"if os.path.exists(image_path):",
"    img = cv2.imread(image_path)",
"    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)",
"    plt.imshow(img)",
"    plt.title('Image from Drive')",
"    plt.axis('off')",
"    plt.show()",
"else:",
"    print('File not found. Please update the path.')",
bt3,
"",
"**In Google Colab**, first mount your Drive:",
"",
bt3 + "python",
"from google.colab import drive",
"drive.mount('/content/drive')",
"img = cv2.imread('/content/drive/MyDrive/sample.jpg')",
bt3,
"",
"## Read 1000 Images",
"",
"> No visual output for this task — images are loaded into a list in memory for batch processing.",
"",
bt3 + "python",
"import glob",
"",
'folder = r"C:\\Users\\USER\\Pictures\\dataset"',
'paths  = glob.glob(folder + "/*.jpg")[:1000]',
"",
"images = []",
"for path in paths:",
"    img = cv2.imread(path)",
"    if img is not None:",
"        images.append(img)",
"",
'print(f"Loaded {len(images)} images")',
bt3,
"",
`**Why check ${bt}if img is not None${bt}?** Some files may be corrupted or in unsupported formats. This prevents a crash.`,
"",
"**Application:** Used in machine learning pipelines when you need to batch-load a dataset for training.",
"",
"## Read Audio & Video",
"",
"### Video",
"",
bt3 + "python",
"cap = cv2.VideoCapture('sample.mp4')",
"",
"frame_count = 0",
"while cap.isOpened():",
"    ret, frame = cap.read()",
"    if not ret:",
"        break",
"    frame_count += 1",
"",
"cap.release()",
'print(f"Total frames: {frame_count}")',
bt3,
"",
"### Audio (using librosa)",
"",
bt3 + "python",
"import librosa",
"import librosa.display",
"",
"y, sr = librosa.load('sample.wav')",
'print(f"Sample rate: {sr} Hz")',
'print(f"Duration   : {len(y)/sr:.2f} seconds")',
"",
"librosa.display.waveshow(y, sr=sr)",
"plt.title('Audio Waveform')",
"plt.show()",
bt3,
"",
"| Format | Library | Use Case |",
"| --- | --- | --- |",
"| Image (jpg/png) | OpenCV / PIL | Static frame analysis |",
"| Video (mp4/avi) | OpenCV VideoCapture | Frame-by-frame processing |",
"| Audio (wav/mp3) | librosa | Waveform, spectrogram analysis |",
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-3-intensity-transformations": [
"## What are Intensity Transformations?",
"",
`Intensity transformations change pixel values based on a mapping function ${bt}s = T(r)${bt}, where ${bt}r${bt} is the input intensity and ${bt}s${bt} is the output intensity. These are **point operations** \u2014 each pixel is processed independently.`,
"",
"> Reference: Gonzalez & Woods, *Digital Image Processing*, Chapter 3 \u2014 Intensity Transformations and Spatial Filtering.",
"",
"## Image Complement",
"",
`The complement of an image inverts every pixel: ${bt}s = L - 1 - r${bt} where L = 256.`,
"",
"Dark regions become bright and vice versa. The **intensity ramp** (Gonzalez Fig 3.7a) is the perfect example — a smooth gradient from black to white, and its complement shows the exact reverse: white to black.",
"",
bt3 + "python",
"import cv2",
"import numpy as np",
"import matplotlib.pyplot as plt",
"",
"img = cv2.imread('intensity_ramp.png', cv2.IMREAD_GRAYSCALE)",
"complement = 255 - img",
"",
"fig, axes = plt.subplots(1, 2, figsize=(10, 5))",
"axes[0].imshow(img, cmap='gray');        axes[0].set_title('Original (Intensity Ramp)')",
"axes[1].imshow(complement, cmap='gray'); axes[1].set_title('Complement')",
"for ax in axes: ax.axis('off')",
"plt.show()",
bt3,
"",
"**Application:** The intensity ramp is the ideal demo for complement — every intensity level is visibly flipped, making s = 255 − r crystal clear.",
"",
"**Drawback:** No new information is created; it is purely a display preference change.",
"",
"## Gamma Correction",
"",
`Gamma correction applies the power-law: ${bt}s = c · r^γ${bt} (Gonzalez Eq. 3.2-9).`,
"",
"- **γ < 1** → brightens the image (expands dark range)",
"- **γ > 1** → darkens the image (compresses dark range)",
"- **γ = 1** → no change",
"",
"> Image used: **Washed-out aerial image** (Gonzalez Fig 3.9) — low contrast, ideal for gamma brightening demo.",
"",
bt3 + "python",
"def gamma_correction(image, gamma=1.0):",
"    normalized = image / 255.0",
"    corrected  = np.power(normalized, gamma) * 255",
"    return corrected.astype(np.uint8)",
"",
"img = cv2.imread('washed_aerial.png', cv2.IMREAD_GRAYSCALE)",
"",
"fig, axes = plt.subplots(1, 3, figsize=(15, 5))",
"axes[0].imshow(img,                        cmap='gray'); axes[0].set_title('Original (γ=1.0)')",
"axes[1].imshow(gamma_correction(img, 0.4), cmap='gray'); axes[1].set_title('γ = 0.4  (Brighter)')",
"axes[2].imshow(gamma_correction(img, 2.5), cmap='gray'); axes[2].set_title('γ = 2.5  (Darker)')",
"for ax in axes: ax.axis('off')",
"plt.tight_layout()",
"plt.show()",
bt3,
"",
"**Benefits:**",
"- Corrects monitor display calibration",
"- Enhances under/over-exposed photographs",
"",
"**Applications:** Monitor calibration, HDR imaging, MRI scan enhancement.",
"",
"| γ value | Effect | Use case |",
"| --- | --- | --- |",
"| γ < 1 | Brightens — expands shadow range | Underexposed / washed-out images |",
"| γ = 1 | No change | Neutral |",
"| γ > 1 | Darkens — compresses highlight range | Overexposed images |",
"",
"## Log Transformation",
"",
`Log transformation: ${bt}s = c · log(1 + r)${bt} (Gonzalez Eq. 3.2-6).`,
"",
"This compresses the high-intensity range and **expands the low-intensity range**, revealing more detail in dark regions.",
"",
"> Image used: **DFT spectrum** (Gonzalez Fig 3.5a) — without log, the spectrum is mostly dark; log transform makes the full pattern visible.",
"",
bt3 + "python",
"img = cv2.imread('dft_no_log.png', cv2.IMREAD_GRAYSCALE)",
"",
"c = 255 / np.log(1 + np.max(img))",
"log_img = c * np.log(1 + img.astype(np.float32))",
"log_img = np.clip(log_img, 0, 255).astype(np.uint8)",
"",
"fig, axes = plt.subplots(1, 2, figsize=(10, 5))",
"axes[0].imshow(img,     cmap='gray'); axes[0].set_title('DFT Spectrum (No Log)')",
"axes[1].imshow(log_img, cmap='gray'); axes[1].set_title('After Log Transform')",
"for ax in axes: ax.axis('off')",
"plt.show()",
bt3,
"",
"| Transformation | Formula | Effect |",
"| --- | --- | --- |",
`| Complement | ${bt}s = 255 - r${bt} | Inverts intensities |`,
`| Gamma (γ<1) | ${bt}s = c·r^γ${bt} | Brightens image |`,
`| Gamma (γ>1) | ${bt}s = c·r^γ${bt} | Darkens image |`,
`| Log | ${bt}s = c·log(1+r)${bt} | Enhances dark regions |`,
"",
"## Image Subtraction",
"",
"By subtracting two images of the same scene, we can find **what changed** between them — specifically which person (or object) is present in the first image but absent in the second.",
"",
"**How it works:**",
"- Take two images of the same scene",
"- Image 1 has the person, Image 2 does not",
`- Apply ${bt}cv2.absdiff()${bt} to find pixel-level differences`,
"- Threshold the result to highlight the changed region",
"",
bt3 + "python",
"import cv2",
"import numpy as np",
"import matplotlib.pyplot as plt",
"",
"# Read both images as grayscale",
"img1 = cv2.imread('scene_with_person.png',    cv2.IMREAD_GRAYSCALE)  # person present",
"img2 = cv2.imread('scene_without_person.png', cv2.IMREAD_GRAYSCALE)  # person absent",
"",
"# Resize to same size if needed",
"img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))",
"",
"# Compute absolute difference",
"diff = cv2.absdiff(img1, img2)",
"",
"# Threshold to get binary mask of changed regions",
"_, diff_thresh = cv2.threshold(diff, 30, 255, cv2.THRESH_BINARY)",
"",
"# Display result",
"fig, axes = plt.subplots(1, 3, figsize=(15, 5))",
"axes[0].imshow(img1,        cmap='gray'); axes[0].set_title('Image 1 — With Person')",
"axes[1].imshow(img2,        cmap='gray'); axes[1].set_title('Image 2 — Without Person')",
"axes[2].imshow(diff_thresh, cmap='gray'); axes[2].set_title('Difference — Absent Person')",
"for ax in axes: ax.axis('off')",
"plt.tight_layout()",
"plt.show()",
bt3,
"",
"**Why threshold = 30?** Small pixel differences (noise, lighting) are ignored. Only significant changes (the person) survive.",
"",
"**Application:** Security surveillance, motion detection, background subtraction in video analytics.",
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-4-histogram": [
"## What is a Histogram?",
"",
"A histogram of an image shows the **frequency distribution of pixel intensities**. The x-axis represents intensity values (0–255) and the y-axis shows how many pixels have that intensity.",
"",
"A dark image has most of its histogram concentrated toward 0. A bright image toward 255. A well-exposed image has a more uniform spread.",
"",
"> Reference: Gonzalez & Woods, *Digital Image Processing*, Section 3.3 — Histogram Processing.",
"",
"## Plotting the Histogram",
"",
bt3 + "python",
"import cv2",
"import matplotlib.pyplot as plt",
"",
"img = cv2.imread('lena.png')",
"img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)",
"",
"fig, axes = plt.subplots(1, 2, figsize=(12, 5))",
"axes[0].imshow(img_rgb)",
"axes[0].set_title('Original Image')",
"axes[0].axis('off')",
"",
"colors = ('red', 'green', 'blue')",
"for i, color in enumerate(colors):",
"    hist = cv2.calcHist([img], [i], None, [256], [0, 256])",
"    axes[1].plot(hist, color=color, label=color.capitalize())",
"",
"axes[1].set_title('RGB Histogram')",
"axes[1].set_xlabel('Pixel Intensity')",
"axes[1].set_ylabel('Frequency')",
"axes[1].legend()",
"axes[1].set_xlim([0, 256])",
"plt.tight_layout()",
"plt.show()",
bt3,
"",
"**Benefits of analyzing a histogram:**",
"- Instantly reveals if an image is under/overexposed",
"- Guides choice of enhancement technique",
"- No need to visually inspect every pixel",
"",
"## Histogram Equalization",
"",
"Histogram equalization redistributes intensities so the cumulative distribution function (CDF) becomes approximately linear — effectively **spreading the pixel values across the full range [0, 255]**.",
"",
"**Formula (Gonzalez Eq. 3.3-8):**",
"",
`${bt}s_k = (L-1) · Σ p_r(r_j)${bt} for j = 0 to k`,
"",
`Where ${bt}p_r(r_j)${bt} is the probability of intensity ${bt}r_j${bt}.`,
"",
bt3 + "python",
"img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)",
"equalized = cv2.equalizeHist(img_gray)",
"",
"fig, axes = plt.subplots(2, 2, figsize=(12, 10))",
"axes[0][0].imshow(img_gray,  cmap='gray'); axes[0][0].set_title('Original Grayscale')",
"axes[0][1].imshow(equalized, cmap='gray'); axes[0][1].set_title('Equalized Image')",
"axes[0][0].axis('off'); axes[0][1].axis('off')",
"",
"axes[1][0].plot(cv2.calcHist([img_gray],  [0], None, [256], [0,256]), color='black')",
"axes[1][0].set_title('Original Histogram'); axes[1][0].set_xlim([0,256])",
"",
"axes[1][1].plot(cv2.calcHist([equalized], [0], None, [256], [0,256]), color='black')",
"axes[1][1].set_title('Equalized Histogram'); axes[1][1].set_xlim([0,256])",
"",
"plt.tight_layout()",
"plt.show()",
bt3,
"",
"## Before vs After",
"",
"| Property | Original | After Equalization |",
"| --- | --- | --- |",
"| Histogram shape | Clustered in narrow range | Spread across 0–255 |",
"| Contrast | Low | High |",
"| Detail visibility | Poor in dark/bright areas | Improved throughout |",
"| Use case | General display | Medical images, low-light photos |",
"",
"**Benefits:**",
"- Simple and automatic — no manual parameter tuning",
"- Works well for low-contrast images",
"",
"**Drawbacks:**",
"- Can over-enhance noise",
"- May produce unnatural-looking results in some images",
"- Treats all regions globally — local contrast improvements need CLAHE",
"",
"**Application:** Medical imaging (X-ray, CT scans), satellite imagery, fingerprint recognition.",
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-5-line-drawing": [
"## What is Line Drawing in CG?",
"",
"In computer graphics, a straight line on screen is drawn by **rasterization** — converting the mathematical line into a series of discrete pixels on a pixel grid. The challenge is to choose which pixels best approximate the ideal line.",
"",
"Two classic algorithms solve this: **DDA** and **Bresenham's**.",
"",
"> These algorithms are implemented in **C++ with OpenGL** and run in **CodeBlocks IDE**.",
"",
"## DDA Algorithm",
"",
"DDA (Digital Differential Analyzer) computes intermediate points using **floating-point arithmetic**.",
"",
"### Algorithm Steps",
"",
`1. Calculate ${bt}dx = x2 - x1${bt} and ${bt}dy = y2 - y1${bt}`,
`2. Choose ${bt}steps = max(|dx|, |dy|)${bt}`,
`3. Compute increments: ${bt}xInc = dx/steps${bt}, ${bt}yInc = dy/steps${bt}`,
`4. Starting from ${bt}(x1, y1)${bt}, plot ${bt}round(x), round(y)${bt} and add increments each step`,
"",
bt3 + "cpp",
"void drawDDA(int x1, int y1, int x2, int y2) {",
"    int dx = x2 - x1, dy = y2 - y1;",
"    int steps = (abs(dx) > abs(dy)) ? abs(dx) : abs(dy);",
"",
"    float xInc = (float)dx / steps;",
"    float yInc = (float)dy / steps;",
"    float x = x1, y = y1;",
"",
"    glBegin(GL_POINTS);",
"    for (int i = 0; i <= steps; i++) {",
"        glVertex2i(round(x), round(y));",
"        x += xInc;",
"        y += yInc;",
"    }",
"    glEnd();",
"}",
bt3,
"",
"**Benefits:** Simple to understand and implement.",
"**Drawback:** Floating-point operations are slower; rounding accumulates error.",
"",
"## Bresenham Algorithm",
"",
"Bresenham's algorithm uses only **integer arithmetic** (addition and subtraction), making it faster and more accurate.",
"",
"### Algorithm Steps",
"",
`1. Calculate ${bt}dx = |x2-x1|${bt}, ${bt}dy = |y2-y1|${bt}`,
`2. Determine step direction ${bt}sx${bt}, ${bt}sy${bt} (+1 or -1)`,
`3. Initialize error term ${bt}err = dx - dy${bt}`,
`4. At each step: plot point, compute ${bt}e2 = 2·err${bt}`,
`   - If ${bt}e2 > -dy${bt}: adjust x`,
`   - If ${bt}e2 < dx${bt}: adjust y`,
`5. Repeat until ${bt}(x1, y1) == (x2, y2)${bt}`,
"",
bt3 + "cpp",
"void drawBresenham(int x1, int y1, int x2, int y2) {",
"    int dx = abs(x2-x1), dy = abs(y2-y1);",
"    int sx = (x1 < x2) ? 1 : -1;",
"    int sy = (y1 < y2) ? 1 : -1;",
"    int err = dx - dy;",
"",
"    glBegin(GL_POINTS);",
"    while (true) {",
"        glVertex2i(x1, y1);",
"        if (x1 == x2 && y1 == y2) break;",
"        int e2 = 2 * err;",
"        if (e2 > -dy) { err -= dy; x1 += sx; }",
"        if (e2 <  dx) { err += dx; y1 += sy; }",
"    }",
"    glEnd();",
"}",
bt3,
"",
"## DDA vs Bresenham",
"",
"| Feature | DDA | Bresenham |",
"| --- | --- | --- |",
"| Arithmetic | Floating-point | Integer only |",
"| Speed | Slower | Faster |",
"| Accuracy | Rounding errors possible | More precise |",
"| Complexity | Simple | Slightly more complex |",
"| Hardware use | Not GPU-friendly | Used in GPU rasterizers |",
"",
"## OpenGL Implementation",
"",
bt3 + "cpp",
"#include <GL/glut.h>",
"#include <cmath>",
"",
"void display() {",
"    glClear(GL_COLOR_BUFFER_BIT);",
"    glPointSize(2.0f);",
"",
"    glColor3f(1.0f, 0.0f, 0.0f);   // Red — DDA line",
"    drawDDA(50, 50, 400, 300);",
"",
"    glColor3f(0.0f, 0.0f, 1.0f);   // Blue — Bresenham line",
"    drawBresenham(50, 300, 400, 50);",
"",
"    glFlush();",
"}",
"",
"int main(int argc, char** argv) {",
"    glutInit(&argc, argv);",
"    glutInitDisplayMode(GLUT_SINGLE | GLUT_RGB);",
"    glutInitWindowSize(500, 400);",
'    glutCreateWindow("DDA vs Bresenham");',
"    glClearColor(1,1,1,1);",
"    glMatrixMode(GL_PROJECTION);",
"    glLoadIdentity();",
"    gluOrtho2D(0, 500, 0, 400);",
"    glutDisplayFunc(display);",
"    glutMainLoop();",
"    return 0;",
"}",
bt3,
"",
"**Application:** Bresenham's algorithm is used inside every modern GPU's rasterizer to draw triangles and lines.",
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-6-geometric-transformations": [
"## What are Geometric Transformations?",
"",
"Geometric transformations change the **spatial arrangement** of pixels in an image — their position, orientation, or size — without changing the pixel values themselves. They are the foundation of image registration, augmented reality, and animation.",
"",
"We apply three fundamental transformations: **Translation**, **Rotation**, and **Scaling**.",
"",
"> All operations use **OpenCV** with a 2×3 transformation matrix. Image used: **lena.png** from Gonzalez's book.",
"",
"## Translation",
"",
`Translation shifts every pixel by ${bt}(tx, ty)${bt} pixels.`,
"",
"**Transformation matrix:**",
bt3,
"M = [[1, 0, tx],",
"     [0, 1, ty]]",
bt3,
"",
bt3 + "python",
"import cv2, numpy as np, matplotlib.pyplot as plt",
"",
"img = cv2.imread('lena.png')",
"img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)",
"h, w = img.shape[:2]",
"",
"tx, ty = 100, 50",
"M_translate = np.float32([[1, 0, tx], [0, 1, ty]])",
"translated  = cv2.warpAffine(img, M_translate, (w, h))",
bt3,
"",
"**Benefits:** Simple — moves objects in the frame without distortion.",
"**Drawback:** Pixels shifted out of the frame boundary are lost.",
"**Application:** Object repositioning in image compositing.",
"",
"## Rotation",
"",
"Rotation turns the image around a center point by a given angle.",
"",
"**Transformation matrix (around center):**",
bt3,
"M = [[cos θ, -sin θ, tx],",
"     [sin θ,  cos θ, ty]]",
bt3,
"",
bt3 + "python",
"angle  = 45",
"center = (w // 2, h // 2)",
"M_rotate = cv2.getRotationMatrix2D(center, angle, scale=1.0)",
"rotated  = cv2.warpAffine(img, M_rotate, (w, h))",
bt3,
"",
"**Benefits:** Corrects skewed/tilted images.",
"**Drawback:** Corners are cropped unless the output canvas is enlarged.",
"**Application:** Document scanner apps, object pose normalization.",
"",
"## Scaling",
"",
`Scaling resizes the image by factors ${bt}fx${bt} (width) and ${bt}fy${bt} (height).`,
"",
bt3 + "python",
"scaled_up   = cv2.resize(img, None, fx=2.0, fy=2.0, interpolation=cv2.INTER_LINEAR)",
"scaled_down = cv2.resize(img, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)",
bt3,
"",
"| Interpolation | Best For |",
"| --- | --- |",
`| ${bt}INTER_NEAREST${bt} | Fastest, pixelated result |`,
`| ${bt}INTER_LINEAR${bt} | Good for scaling up |`,
`| ${bt}INTER_AREA${bt} | Best for scaling down |`,
`| ${bt}INTER_CUBIC${bt} | High quality, slower |`,
"",
"## Transformation Matrix",
"",
"All three transformations can be expressed as a single 2×3 affine matrix:",
"",
bt3,
"[x']   [a  b  tx] [x]",
"[y'] = [c  d  ty] [y]",
"                  [1]",
bt3,
"",
"- **Translation:** a=d=1, b=c=0, tx and ty set the shift",
"- **Rotation:** a=cosθ, b=-sinθ, c=sinθ, d=cosθ",
"- **Scaling:** a=sx, d=sy, b=c=0",
"",
bt3 + "python",
"fig, axes = plt.subplots(1, 5, figsize=(20, 5))",
"axes[0].imshow(img);         axes[0].set_title('Original')",
"axes[1].imshow(translated);  axes[1].set_title('Translated')",
"axes[2].imshow(rotated);     axes[2].set_title('Rotated 45°')",
"axes[3].imshow(scaled_up);   axes[3].set_title('Scaled Up 2x')",
"axes[4].imshow(scaled_down); axes[4].set_title('Scaled Down 0.5x')",
"for ax in axes: ax.axis('off')",
"plt.tight_layout()",
"plt.show()",
bt3,
"",
"**Application:** Image stitching for panoramas, face alignment, data augmentation for deep learning.",
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-7-otsu-thresholding": [
"## What is Thresholding?",
"",
"Thresholding is the simplest method of **image segmentation**. It converts a grayscale image to a binary (black & white) image by comparing each pixel to a threshold value T:",
"",
`- If ${bt}pixel > T${bt} → white (255)`,
`- If ${bt}pixel ≤ T${bt} → black (0)`,
"",
"The key question is: **how do we choose the best T automatically?** That is what Otsu's method solves.",
"",
"> Reference: Gonzalez & Woods, *Digital Image Processing*, Section 10.3 — Thresholding.",
"",
"## Otsu's Theory",
"",
"Otsu's method finds the threshold T that **maximizes the inter-class variance** (variance between the foreground and background pixel groups).",
"",
"**Given:**",
`- ${bt}w0(T)${bt} = weight (fraction of pixels) in class 0 (background)`,
`- ${bt}w1(T)${bt} = weight in class 1 (foreground)`,
`- ${bt}μ0(T)${bt}, ${bt}μ1(T)${bt} = mean intensities of each class`,
"",
"**Otsu's criterion:**",
"",
`${bt}σ²_between = w0 · w1 · (μ0 - μ1)²${bt}`,
"",
`The optimal threshold is ${bt}T* = argmax σ²_between(T)${bt}.`,
"",
"## Algorithm Steps",
"",
"1. Compute the normalized histogram (probability of each intensity 0–255)",
"2. For each possible threshold T from 0 to 255:",
`   - Compute ${bt}w0${bt}, ${bt}w1${bt} (cumulative probabilities)`,
`   - Compute ${bt}μ0${bt}, ${bt}μ1${bt} (cumulative means)`,
`   - Compute inter-class variance ${bt}σ²_between${bt}`,
`3. Select T with the maximum ${bt}σ²_between${bt}`,
"4. Apply threshold to produce binary image",
"",
"## Implementation",
"",
"### Manual implementation",
"",
bt3 + "python",
"import cv2, numpy as np, matplotlib.pyplot as plt",
"",
"def otsu_threshold(image):",
"    hist, _ = np.histogram(image.flatten(), 256, [0, 256])",
"    total   = image.size",
"    prob    = hist / total",
"",
"    best_thresh, max_var = 0, 0",
"    w0, mean0 = 0.0, 0.0",
"",
"    for t in range(256):",
"        w0    += prob[t]",
"        w1     = 1 - w0",
"        if w0 == 0 or w1 == 0: continue",
"        mean0  = (mean0 * (w0 - prob[t]) + t * prob[t]) / w0",
"        mean1  = (np.sum(np.arange(t+1, 256) * prob[t+1:256])) / w1",
"        between_var = w0 * w1 * (mean0 - mean1) ** 2",
"        if between_var > max_var:",
"            max_var, best_thresh = between_var, t",
"",
"    return best_thresh",
"",
"img = cv2.imread('lena.png', cv2.IMREAD_GRAYSCALE)",
"manual_T = otsu_threshold(img)",
'print(f"Manual Otsu Threshold: {manual_T}")',
bt3,
"",
"### OpenCV built-in",
"",
bt3 + "python",
"cv_T, binary = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)",
'print(f"OpenCV Otsu Threshold: {int(cv_T)}")',
bt3,
"",
bt3 + "python",
"plt.hist(img.flatten(), bins=256, range=[0,256], color='gray', alpha=0.7)",
"plt.axvline(x=cv_T, color='red', linewidth=2, label=f'T = {int(cv_T)}')",
"plt.title('Histogram with Otsu Threshold')",
"plt.legend()",
"plt.show()",
bt3,
"",
"**Benefits:**",
"- Fully automatic — no manual threshold selection",
"- Works well for bimodal histograms (clear foreground/background separation)",
"",
"**Drawbacks:**",
"- Fails on non-bimodal histograms",
"- Sensitive to noise and uneven lighting",
"",
"**Application:** Document scanning, cell counting in microscopy, fingerprint binarization.",
"",
"## Figure 10.36",
"",
"**Original Septagon with Gaussian noise variants** — shows the input images used for thresholding experiments.",
"",
"- **(a)** Original clean septagon",
"- **(b)** Gaussian noise added (mean=0, σ=10) — mild noise",
"- **(c)** Gaussian noise added (mean=0, σ=50) — heavy noise",
"",
"## Figure 10.37",
"",
"Otsu applied to two test images — each shown with its **histogram and resulting binary image**:",
"",
"- **(a)** Septagon with Gaussian noise σ=10 — bimodal histogram, Otsu works well",
"- **(b)** Intensity ramp — flat histogram, shows limitation of global thresholding",
"",
"## Figure 10.38",
"",
"**Noisy fingerprint** — the classic Otsu demo image. The bimodal histogram (ridge peaks vs valley peaks) makes it an ideal case for automatic thresholding.",
"",
"## Figure 10.39",
"",
"**Polymersomes image** — circular vesicle structures. Otsu separates the bright vesicles from the dark background automatically.",
"",
"## Figure 10.40",
"",
"**Large septagon with heavy noise (σ=50)** — demonstrates how Otsu struggles when noise significantly corrupts the histogram's bimodal shape.",
"",
"## Figure 10.41",
"",
"**Small septagon with mild noise (σ=10)** — Otsu still performs well when noise is low and the two classes remain separable in the histogram.",
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-8-cohen-sutherland": [
"## What is Line Clipping?",
"",
"Line clipping is the process of removing parts of a line that fall **outside a defined rectangular viewport**. Only the portion of the line visible within the window is drawn.",
"",
"> Implemented in **C++ with OpenGL** in **CodeBlocks IDE**. Reference: Foley et al., *Computer Graphics: Principles and Practice*.",
"",
"## Algorithm Steps",
"",
`1. Compute outcodes ${bt}OC1${bt} and ${bt}OC2${bt} for both endpoints`,
`2. If ${bt}OC1 | OC2 == 0${bt} — both inside → **trivially accept**, draw line`,
`3. If ${bt}OC1 & OC2 != 0${bt} — both outside same region → **trivially reject**, discard line`,
"4. Otherwise — line is partially inside. Pick an endpoint outside the window:",
"   - Find which boundary it violates (LEFT, RIGHT, TOP, BOTTOM)",
"   - Compute the intersection point with that boundary",
"   - Replace the outside endpoint with the intersection",
"5. Repeat until trivially accepted or rejected",
"",
"## Implementation",
"",
bt3 + "cpp",
"#include <GL/glut.h>",
"#include <iostream>",
"using namespace std;",
"",
"const float xmin = 100, xmax = 400, ymin = 100, ymax = 300;",
"",
"typedef int OutCode;",
"const int INSIDE = 0, LEFT = 1, RIGHT = 2, BOTTOM = 4, TOP = 8;",
"",
"OutCode computeOutCode(float x, float y) {",
"    OutCode code = INSIDE;",
"    if      (x < xmin) code |= LEFT;",
"    else if (x > xmax) code |= RIGHT;",
"    if      (y < ymin) code |= BOTTOM;",
"    else if (y > ymax) code |= TOP;",
"    return code;",
"}",
"",
"void cohenSutherland(float x1, float y1, float x2, float y2) {",
"    OutCode oc1 = computeOutCode(x1, y1);",
"    OutCode oc2 = computeOutCode(x2, y2);",
"",
"    while (true) {",
"        if (!(oc1 | oc2)) {           // trivially accept",
"            glBegin(GL_LINES);",
"            glVertex2f(x1, y1);",
"            glVertex2f(x2, y2);",
"            glEnd();",
"            break;",
"        } else if (oc1 & oc2) {       // trivially reject",
"            break;",
"        } else {",
"            float x, y;",
"            OutCode ocOut = oc1 ? oc1 : oc2;",
"            if      (ocOut & TOP)    { x = x1 + (x2-x1)*(ymax-y1)/(y2-y1); y = ymax; }",
"            else if (ocOut & BOTTOM) { x = x1 + (x2-x1)*(ymin-y1)/(y2-y1); y = ymin; }",
"            else if (ocOut & RIGHT)  { y = y1 + (y2-y1)*(xmax-x1)/(x2-x1); x = xmax; }",
"            else                     { y = y1 + (y2-y1)*(xmin-x1)/(x2-x1); x = xmin; }",
"            if (ocOut == oc1) { x1 = x; y1 = y; oc1 = computeOutCode(x1, y1); }",
"            else              { x2 = x; y2 = y; oc2 = computeOutCode(x2, y2); }",
"        }",
"    }",
"}",
bt3,
"",
"**Key insight:** The trivial accept/reject tests make this algorithm very fast — most lines in a typical scene are either fully inside or fully outside the viewport.",
"",
"**Application:** Used in every graphics pipeline — GPU rasterizers clip all primitives to the view frustum before rasterization.",
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-9-kmeans-clustering": [
"## What is Clustering?",
"",
"Clustering is an **unsupervised machine learning** technique that groups similar data points together without using labels. In image processing, K-Means clustering groups pixels by color similarity, enabling **image segmentation** — dividing an image into meaningful regions.",
"",
"> Image used: **lena.png** from Gonzalez's Digital Image Processing.",
"",
"## K-Means Algorithm",
"",
`K-Means partitions ${bt}n${bt} data points into ${bt}k${bt} clusters by minimizing **within-cluster variance**.`,
"",
"### Algorithm Steps",
"",
`1. Choose ${bt}k${bt} — the number of clusters (segments)`,
`2. Randomly initialize ${bt}k${bt} centroids`,
"3. **Assignment step:** assign each pixel to the nearest centroid (Euclidean distance in RGB space)",
"4. **Update step:** recompute each centroid as the mean of all assigned pixels",
"5. Repeat steps 3–4 until centroids stop changing (convergence)",
"",
`**Convergence criterion:** ${bt}||new_centroids - old_centroids|| < ε${bt} or max iterations reached.`,
"",
"## Implementation",
"",
"### Manual implementation",
"",
bt3 + "python",
"import cv2, numpy as np, matplotlib.pyplot as plt",
"",
"def kmeans_manual(image, k=3, max_iter=10):",
"    pixels = image.reshape(-1, 3).astype(np.float32)",
"    np.random.seed(42)",
"    idx = np.random.choice(len(pixels), k, replace=False)",
"    centroids = pixels[idx]",
"",
"    for _ in range(max_iter):",
"        distances = np.linalg.norm(pixels[:, np.newaxis] - centroids, axis=2)",
"        labels    = np.argmin(distances, axis=1)",
"        new_centroids = np.array([pixels[labels==i].mean(axis=0) for i in range(k)])",
"        if np.allclose(centroids, new_centroids): break",
"        centroids = new_centroids",
"",
"    segmented = centroids[labels].astype(np.uint8)",
"    return segmented.reshape(image.shape)",
bt3,
"",
"### OpenCV built-in",
"",
bt3 + "python",
"def kmeans_opencv(image, k=3):",
"    pixels   = image.reshape(-1, 3).astype(np.float32)",
"    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 10, 1.0)",
"    _, labels, centers = cv2.kmeans(pixels, k, None, criteria, 10,",
"                                    cv2.KMEANS_RANDOM_CENTERS)",
"    centers   = np.uint8(centers)",
"    segmented = centers[labels.flatten()]",
"    return segmented.reshape(image.shape)",
bt3,
"",
"## Effect of K Values",
"",
bt3 + "python",
"img = cv2.imread('lena.png')",
"img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)",
"",
"fig, axes = plt.subplots(1, 4, figsize=(20, 5))",
"axes[0].imshow(img); axes[0].set_title('Original')",
"",
"for i, k in enumerate([2, 3, 5]):",
"    result = kmeans_manual(img, k=k)",
"    axes[i+1].imshow(result)",
"    axes[i+1].set_title(f'K = {k}')",
"",
"for ax in axes: ax.axis('off')",
"plt.tight_layout()",
"plt.show()",
bt3,
"",
"| K Value | Result |",
"| --- | --- |",
"| K = 2 | Two regions — rough foreground/background split |",
"| K = 3 | Three color regions, cleaner segmentation |",
"| K = 5 | More detailed color regions |",
"| K = 10+ | Diminishing returns, high computation cost |",
"",
"**Benefits:**",
"- Simple to understand and implement",
"- Works well for color-based segmentation",
"",
"**Drawbacks:**",
`- Requires choosing ${bt}k${bt} in advance`,
"- Sensitive to initial centroid placement",
"- Can converge to local minima",
"",
"**Application:** Image compression, medical image segmentation, remote sensing image analysis.",
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-10-flood-fill": [
"## What is Fill Algorithm?",
"",
"Fill algorithms color a **region** in a raster image. They start from a seed pixel and spread to neighboring pixels, either stopping at a boundary color (Boundary Fill) or replacing a specific fill color (Flood Fill).",
"",
"> Implemented in **C++ with OpenGL** in **CodeBlocks IDE**. Applied for **object detection** — identifying and coloring enclosed regions.",
"",
"## Boundary Fill",
"",
"Boundary Fill colors all pixels in a region until it hits pixels of the **boundary color**.",
"",
"### Algorithm",
"",
`- Start at seed pixel ${bt}(x, y)${bt}`,
`- If current pixel is NOT the boundary color AND NOT already the fill color:`,
"  - Color it with the fill color",
"  - Recursively fill its 4 (or 8) neighbors",
"",
bt3 + "cpp",
"void boundaryFill4(int x, int y, float* fillColor, float* borderColor) {",
"    float curr[3];",
"    glReadPixels(x, y, 1, 1, GL_RGB, GL_FLOAT, curr);",
"",
"    bool isBorder = (curr[0]==borderColor[0] && curr[1]==borderColor[1] && curr[2]==borderColor[2]);",
"    bool isFilled = (curr[0]==fillColor[0]   && curr[1]==fillColor[1]   && curr[2]==fillColor[2]);",
"",
"    if (!isBorder && !isFilled) {",
"        glColor3fv(fillColor);",
"        glBegin(GL_POINTS); glVertex2i(x, y); glEnd();",
"        glFlush();",
"        boundaryFill4(x+1, y, fillColor, borderColor);",
"        boundaryFill4(x-1, y, fillColor, borderColor);",
"        boundaryFill4(x,   y+1, fillColor, borderColor);",
"        boundaryFill4(x,   y-1, fillColor, borderColor);",
"    }",
"}",
bt3,
"",
"**4-connected** fill spreads to top/bottom/left/right neighbors only.",
"**8-connected** fill also spreads to diagonal neighbors — fills corners better but may leak through diagonal boundaries.",
"",
"## Flood Fill",
"",
`Flood Fill replaces all pixels of the **target color** (the color at the seed) with the fill color — no explicit boundary needed.`,
"",
"### Algorithm",
"",
`- Start at seed pixel ${bt}(x, y)${bt}`,
"- Record the target color (current pixel's color)",
`- If current pixel's color == target color AND != fill color:`,
"  - Color it with fill color",
"  - Recursively fill 4 neighbors",
"",
bt3 + "cpp",
"void floodFill4(int x, int y, float* fillColor, float* targetColor) {",
"    float curr[3];",
"    glReadPixels(x, y, 1, 1, GL_RGB, GL_FLOAT, curr);",
"",
"    bool isTarget = (curr[0]==targetColor[0] && curr[1]==targetColor[1] && curr[2]==targetColor[2]);",
"    bool isFilled = (curr[0]==fillColor[0]   && curr[1]==fillColor[1]   && curr[2]==fillColor[2]);",
"",
"    if (isTarget && !isFilled) {",
"        glColor3fv(fillColor);",
"        glBegin(GL_POINTS); glVertex2i(x, y); glEnd();",
"        glFlush();",
"        floodFill4(x+1, y, fillColor, targetColor);",
"        floodFill4(x-1, y, fillColor, targetColor);",
"        floodFill4(x,   y+1, fillColor, targetColor);",
"        floodFill4(x,   y-1, fillColor, targetColor);",
"    }",
"}",
bt3,
"",
"## Comparison",
"",
"| Feature | Boundary Fill | Flood Fill |",
"| --- | --- | --- |",
"| Stop condition | Hits boundary color | Leaves target color |",
"| Boundary needed | Yes — explicit border | No — replaces color region |",
"| Use case | Drawn shapes with clear borders | Replacing a specific color area |",
"| Risk | Leaks if boundary has gaps | May overfill if target color is widespread |",
"",
"**Application:** Paint bucket tool in image editors, object region detection, maze solving, game map flood fill (e.g. fog of war).",
].join("\n"),

// ─────────────────────────────────────────────────────────────────────────────
"cg-lab-11-edge-detection": [
"## What is an Edge?",
"",
"An edge in an image is a **significant local change in intensity** — a boundary between regions with different brightness or color. Edges correspond to meaningful features like object boundaries, surface creases, and depth discontinuities.",
"",
"Mathematically, edges are detected using **derivatives** of the image intensity function.",
"",
"> Reference: Gonzalez & Woods, *Digital Image Processing*, Chapter 10 — Image Segmentation (Edge Detection).",
"",
"## Laplacian of Gaussian",
"",
"LoG (Gonzalez Eq. 10.3-7) applies a Gaussian blur first (to suppress noise), then uses the Laplacian (second derivative) to find edges at **zero-crossings**:",
"",
bt3 + "python",
"blurred = cv2.GaussianBlur(img, (5, 5), 0)",
"log     = cv2.Laplacian(blurred, cv2.CV_64F)",
"log     = np.clip(np.abs(log), 0, 255).astype(np.uint8)",
bt3,
"",
"**Benefits:** Detects edges more precisely as zero-crossings are localized.",
"**Drawback:** Second derivative amplifies noise — Gaussian pre-filtering is essential.",
"",
"## Canny Detector",
"",
"Canny (Gonzalez Section 10.4) is the **gold standard** edge detector. It has four stages:",
"",
"1. **Gaussian smoothing** — noise reduction",
"2. **Gradient computation** — Sobel in x and y",
"3. **Non-maximum suppression** — thin edges to 1-pixel width",
"4. **Hysteresis thresholding** — two thresholds (low, high) to keep only strong, connected edges",
"",
bt3 + "python",
"canny = cv2.Canny(img, threshold1=50, threshold2=150)",
bt3,
"",
"**Threshold tuning:**",
bt3 + "python",
"for low, high in [(30, 100), (50, 150), (100, 200)]:",
"    result = cv2.Canny(img, low, high)",
"    plt.imshow(result, cmap='gray')",
"    plt.title(f'Canny T1={low}, T2={high}')",
"    plt.show()",
bt3,
"",
"## Comparison",
"",
"| Detector | Kernel Size | Noise Tolerance | Edge Quality | Speed |",
"| --- | --- | --- | --- | --- |",
"| LoG | 5×5 | High | Precise (zero-crossings) | Medium |",
"| Canny | Multi-stage | Highest | Best (thin, connected) | Slowest |",
"",
"**Applications:** Object detection, image segmentation preprocessing, autonomous vehicles (road lane detection), medical imaging (tumor boundary detection).",
].join("\n"),

};
